import { test, expect, apiAs, customerWithRequest, DEMO, signIn, uniquePhone, expectNoA11yViolations } from './fixtures'

test.describe('customer account', () => {
  test('log in from the header, see appointments, log out', async ({ page, guard }) => {
    guard.allow(/http 401: POST \/api\/auth\/login/)
    guard.allow(/status of 401/)
    const { phone, password, firstName, request } = await customerWithRequest()
    await page.goto('/')
    const entry = page.locator('header').getByRole('button', { name: 'Log in' }).locator('visible=true').first()
    await entry.click()
    const d = page.locator('dialog[open]')
    await d.getByLabel('Mobile number').fill(phone)
    await d.getByLabel('Password', { exact: true }).fill('wrong-password')
    await d.getByRole('button', { name: 'Log in', exact: true }).click()
    await expect(d.getByRole('alert')).toContainText('don’t match')
    await d.getByLabel('Password', { exact: true }).fill(password)
    await d.getByRole('button', { name: 'Log in', exact: true }).click()
    await expect(page.locator('dialog[open]')).toHaveCount(0)
    await page.locator('header').getByRole('link', { name: 'My appointments' }).locator('visible=true').first().click()
    await expect(page.getByRole('heading', { level: 1 })).toContainText(`Hello, ${firstName}`)
    await expect(page.locator('li', { hasText: request.reference })).toContainText('Awaiting confirmation')
    await expectNoA11yViolations(page, 'account')
    await page.getByRole('button', { name: 'Log out' }).click()
    await expect(page.getByRole('heading', { level: 1 })).toContainText('Log in to see your appointments')
  })

  test('cancel an upcoming request', async ({ page }) => {
    const { phone, password, request } = await customerWithRequest()
    await signIn(page, { phone, password })
    await page.goto('/account')
    const card = page.locator('li', { hasText: request.reference })
    await card.getByRole('button', { name: 'Cancel request' }).click()
    await card.getByRole('button', { name: 'Keep it' }).click()
    await expect(card).toContainText('Awaiting confirmation')
    await card.getByRole('button', { name: 'Cancel request' }).click()
    await card.getByRole('button', { name: 'Yes, cancel it' }).click()
    await expect(page.locator('li', { hasText: request.reference })).toContainText('Cancelled')
    await expect(page.getByRole('heading', { name: 'Past and closed' })).toBeVisible()
  })

  test('edit profile, language and password', async ({ page, guard }) => {
    guard.allow(/http (400|409): (PATCH \/api\/account|POST \/api\/account\/password)/)
    guard.allow(/status of (400|409)/)
    const { phone, password } = await customerWithRequest()
    const other = await customerWithRequest()
    await other.ctx.patch('/api/account', { data: { email: `taken${phone}@example.com` } })
    await signIn(page, { phone, password })
    await page.goto('/account')

    await page.getByLabel('Email').fill(`taken${phone}@example.com`)
    await page.getByRole('button', { name: 'Save changes' }).click()
    await expect(page.getByText('This email is already used by another account.')).toBeVisible()
    await page.getByLabel('Email').fill(`me${phone}@example.com`)
    await page.getByLabel('First name').fill('Renamed')
    await page.getByRole('button', { name: 'Save changes' }).click()
    await expect(page.getByText('Changes saved.')).toBeVisible()
    await expect(page.getByRole('heading', { level: 1 })).toContainText('Hello, Renamed')

    await page.getByLabel('Current password').fill('not-my-password')
    await page.getByLabel('New password').fill('a-new-password-1')
    await page.getByRole('button', { name: 'Update password' }).click()
    await expect(page.getByText('Your current password isn’t right.')).toBeVisible()
    await page.getByLabel('Current password').fill(password)
    await page.getByRole('button', { name: 'Update password' }).click()
    await expect(page.getByText('Password changed.', { exact: false })).toBeVisible()

    await page.getByLabel('Preferred language').selectOption('ar')
    await page.getByRole('button', { name: 'Save changes' }).click()
    await expect(page.locator('html')).toHaveAttribute('dir', 'rtl')
  })

  test('reset a forgotten password with a code from the branch', async ({ page, guard }) => {
    guard.allow(/http 400: POST \/api\/auth\/reset/)
    guard.allow(/status of 400/)
    const { phone } = await customerWithRequest()
    const staff = await apiAs(DEMO.staff)
    const customers = (await (await staff.get(`/api/admin/customers?q=${phone.slice(-7)}`)).json()) as { customers: { id: number }[] }
    const { code } = (await (await staff.post(`/api/admin/users/${customers.customers[0].id}/reset-code`, { data: {} })).json()) as { code: string }
    await staff.dispose()

    await page.goto('/account')
    await page.getByRole('button', { name: 'Forgot your password?' }).click()
    await expect(page.getByRole('link', { name: /New Cairo/ })).toBeVisible()
    await page.getByLabel('Mobile number').fill(phone)
    await page.getByLabel('Reset code').fill('AAAA-BBBB')
    await page.getByLabel('New password').fill('brand-new-password')
    await page.getByRole('button', { name: 'Save new password' }).click()
    await expect(page.getByRole('alert')).toContainText('isn’t valid')
    await page.getByLabel('Reset code').fill(code.toLowerCase())
    await page.getByRole('button', { name: 'Save new password' }).click()
    await expect(page.getByRole('heading', { level: 1 })).toContainText('Hello,')
  })

  test('someone new can create an account from the header', async ({ page }) => {
    await page.goto('/')
    await page.locator('header').getByRole('button', { name: 'Log in' }).locator('visible=true').first().click()
    const d = page.locator('dialog[open]')
    await d.getByRole('tab', { name: 'New account' }).click()
    await d.getByLabel('First name').fill('Heba')
    await d.getByLabel('Mobile number').fill(uniquePhone())
    await d.getByLabel('Password', { exact: true }).fill('heba-password-1')
    await d.getByRole('button', { name: 'Create account' }).click()
    await expect(page.locator('dialog[open]')).toHaveCount(0)
    await expect(page.locator('header').getByRole('link', { name: 'My appointments' }).locator('visible=true').first()).toBeVisible()
  })

  test('signing up with a number that already has an account leads to log in', async ({ page, guard }) => {
    guard.allow(/http 409: POST \/api\/auth\/signup/)
    guard.allow(/status of 409/)
    const { phone, password, firstName } = await customerWithRequest()
    await page.goto('/account')
    const main = page.locator('main')
    // The two tabs follow the arrow keys.
    await main.getByRole('tab', { name: 'Log in' }).focus()
    await page.keyboard.press('ArrowLeft')
    await expect(main.getByRole('tab', { name: 'New account' })).toBeFocused()
    await expect(main.getByRole('tab', { name: 'New account' })).toHaveAttribute('aria-selected', 'true')
    await expect(main.getByRole('tabpanel')).toContainText('Create your account')

    await main.getByLabel('First name').fill('Someone')
    await main.getByLabel('Mobile number').fill(phone)
    await main.getByLabel('Password', { exact: true }).fill('another-password')
    await main.getByRole('button', { name: 'Create account' }).click()
    await expect(main.getByText('An account with this number already exists.', { exact: false })).toBeVisible()
    await main.getByRole('button', { name: 'Log in with this number' }).click()
    await expect(main.getByRole('tab', { name: 'Log in' })).toHaveAttribute('aria-selected', 'true')
    await expect(main.getByLabel('Mobile number')).toHaveValue(phone)
    await main.getByLabel('Password', { exact: true }).fill(password)
    await main.getByRole('button', { name: 'Log in', exact: true }).click()
    await expect(page.getByRole('heading', { level: 1 })).toContainText(`Hello, ${firstName}`)
  })
})
