import { test, expect, cairoDate, apiAs, DEMO, signIn, signOut, uniquePhone, expectNoHorizontalOverflow } from './fixtures'
import type { Page } from '@playwright/test'

const dialog = (page: Page) => page.locator('dialog[open]')

async function openRequest(page: Page) {
  if (test.info().project.name === 'mobile') await page.locator('main').getByRole('button', { name: 'Request an appointment' }).first().click()
  else await page.locator('header').getByRole('button', { name: 'Request an appointment' }).click()
  await expect(dialog(page)).toBeVisible()
}

async function next(page: Page) {
  await dialog(page).getByRole('button', { name: 'Continue' }).click()
}

async function fillToDetails(page: Page, { branch = 'New Cairo', search = 'chrome', service = 'Chrome finish', date = cairoDate(2), time = '17:30' } = {}) {
  await dialog(page).getByText(branch, { exact: true }).click()
  await next(page)
  await dialog(page).getByLabel('Search the menu').fill(search)
  await dialog(page).getByLabel(service).check()
  await dialog(page).getByLabel('Search the menu').fill('')
  await next(page)
  await dialog(page).getByLabel('Preferred date').fill(date)
  await dialog(page).getByLabel('Preferred time').fill(time)
  await next(page)
  await expect(dialog(page).getByRole('heading', { name: 'How can the branch reach you?' })).toBeVisible()
}

test.describe('customer', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/')
    await page.evaluate(() => sessionStorage.clear())
    await page.reload()
  })

  test('a new customer creates an account inside the request and sends it', async ({ page }) => {
    await openRequest(page)
    await fillToDetails(page)
    // Signed out: the account form is the only way forward.
    await expect(dialog(page).getByRole('button', { name: 'Continue' })).toHaveCount(0)
    await dialog(page).getByRole('button', { name: 'Create account' }).click()
    await expect(dialog(page).getByText('Enter your first name.')).toBeVisible()
    await expect(dialog(page).getByText('Enter your mobile number.')).toBeVisible()
    await expect(dialog(page).getByText('Enter your password.')).toBeVisible()

    const phone = uniquePhone()
    await dialog(page).getByLabel('First name').fill('Laila')
    await dialog(page).getByLabel('Mobile number').fill(phone)
    await dialog(page).getByLabel('Password', { exact: true }).fill('short')
    await dialog(page).getByRole('button', { name: 'Create account' }).click()
    await expect(dialog(page).getByText('Use at least 8 characters.')).toBeVisible()
    await dialog(page).getByLabel('Password', { exact: true }).fill('lush-laila-2026')
    await dialog(page).getByRole('button', { name: 'Create account' }).click()
    await expect(dialog(page).getByText('Signed in as Laila')).toBeVisible()

    await dialog(page).getByLabel('Notes').fill('Soft pink base, please.')
    await next(page)
    await expect(dialog(page).getByRole('heading', { name: 'Review your request' })).toBeVisible()
    await expect(dialog(page).getByText('Your appointment is confirmed once the branch replies.')).toBeVisible()
    await dialog(page).getByRole('button', { name: 'Send request' }).click()
    await expect(dialog(page).getByRole('heading', { name: 'Request sent' })).toBeVisible()
    const reference = (await dialog(page).getByText(/LSH-[0-9A-Z]{6}/).textContent())!.match(/LSH-[0-9A-Z]{6}/)![0]

    await dialog(page).getByRole('button', { name: 'View my appointments' }).click()
    await expect(page).toHaveURL(/\/account$/)
    const card = page.locator('li', { hasText: reference })
    await expect(card).toContainText('Awaiting confirmation')
    await expect(card).toContainText('Chrome finish')
    await expectNoHorizontalOverflow(page)

    // The account works next time: sign out, then log in from the header.
    await page.getByRole('button', { name: 'Log out' }).click()
    await expect(page.getByRole('heading', { level: 1 })).toContainText('Log in to see your appointments')
    const main = page.locator('main')
    await main.getByLabel('Mobile number').fill(phone)
    await main.getByLabel('Password', { exact: true }).fill('lush-laila-2026')
    await main.getByRole('button', { name: 'Log in', exact: true }).click()
    await expect(page.getByRole('heading', { level: 1 })).toContainText('Hello, Laila')
  })

  test('each step explains what is missing', async ({ page }) => {
    await openRequest(page)
    await next(page)
    await expect(dialog(page).getByText('Choose a branch to continue.')).toBeVisible()
    await expect(dialog(page).locator('#req-branchId')).toBeFocused()
    await dialog(page).getByText('Heliopolis', { exact: true }).click()
    await next(page)
    await next(page)
    await expect(dialog(page).getByText('Choose at least one service, or select “Help me choose”.')).toBeVisible()
    await dialog(page).getByLabel('Search the menu').fill('zzzz')
    await expect(dialog(page).getByText('Nothing on the menu matches “zzzz”.', { exact: false })).toBeVisible()
    await dialog(page).getByLabel('Search the menu').fill('')
    await dialog(page).getByText('Help me choose', { exact: true }).click()
    await next(page)
    await next(page)
    await expect(dialog(page).getByText('Choose a preferred date.')).toBeVisible()
    await dialog(page).getByLabel('Preferred date').fill(cairoDate(-1))
    await next(page)
    await expect(dialog(page).getByText('That date has passed.', { exact: false })).toBeVisible()
    await dialog(page).getByLabel('Preferred date').fill(cairoDate(400))
    await next(page)
    await expect(dialog(page).getByText('Choose a date within the next 12 months.')).toBeVisible()
    await dialog(page).getByLabel('Preferred date').fill(cairoDate(0))
    await dialog(page).getByLabel('Preferred time').fill('00:00')
    await next(page)
    await expect(dialog(page).getByText('That time has already passed today in Cairo.', { exact: false })).toBeVisible()
    await dialog(page).getByText('I’m flexible on time that day').click()
    await expect(dialog(page).getByLabel('Preferred time')).toBeDisabled()
    await next(page)
    await expect(dialog(page).getByRole('heading', { name: 'How can the branch reach you?' })).toBeVisible()
  })

  test('a look from the gallery travels into the request', async ({ page }) => {
    await page.goto('/#work')
    await page.getByRole('button', { name: 'View Cat-eye plum' }).click()
    await dialog(page).getByRole('button', { name: 'Enquire about this look' }).click()
    await expect(dialog(page).getByRole('heading', { name: 'Choose your branch' })).toBeVisible()
    await dialog(page).getByText('New Cairo', { exact: true }).click()
    await next(page)
    await expect(dialog(page).getByText('LK-04')).toBeVisible()
    await expect(dialog(page).getByRole('button', { name: /Remove: Cat-eye design/ })).toBeVisible()
  })

  test('choosing a branch in Locations preselects it', async ({ page }) => {
    await page.goto('/#locations')
    await page.getByRole('button', { name: 'Request an appointment at Heliopolis' }).click()
    await expect(dialog(page).getByRole('heading', { name: 'What would you like?' })).toBeVisible()
    await expect(dialog(page).getByText('Heliopolis', { exact: true })).toBeVisible()
  })

  test('a bridal enquiry collects the event date and group size', async ({ page }) => {
    await signIn(page, DEMO.customer)
    await page.goto('/#bridal')
    await page.reload()
    await page.getByRole('button', { name: 'Enquire about the Golden Package' }).click()
    await expect(dialog(page).getByText('Plan a bridal appointment')).toBeVisible()
    await dialog(page).getByText('Heliopolis', { exact: true }).click()
    await next(page)
    await expect(dialog(page).getByRole('button', { name: /Remove: Golden Package/ })).toBeVisible()
    await next(page)
    await dialog(page).getByLabel('Preferred date').fill(cairoDate(5))
    await dialog(page).getByLabel('Preferred time').fill('11:00')
    await dialog(page).getByLabel('How many of you, including you?').fill('45')
    await dialog(page).getByLabel('Wedding or event date').fill(cairoDate(9))
    await next(page)
    await expect(dialog(page).getByText('Enter a number from 1 to 30.')).toBeVisible()
    await dialog(page).getByLabel('How many of you, including you?').fill('4')
    await next(page)
    await next(page)
    await expect(dialog(page).getByText('Group size: 4')).toBeVisible()
    await dialog(page).getByRole('button', { name: 'Send request' }).click()
    await expect(dialog(page).getByRole('heading', { name: 'Request sent' })).toBeVisible()
    await dialog(page).getByRole('button', { name: 'Done' }).click()
    await expect(dialog(page)).toHaveCount(0)
    // A finished request doesn't linger: the next one starts fresh.
    await openRequest(page)
    await expect(dialog(page).getByRole('heading', { name: 'Choose your branch' })).toBeVisible()
    await expect(dialog(page).getByText('Plan a bridal appointment')).toHaveCount(0)
  })

  test('switching language mid-request keeps every answer', async ({ page }) => {
    await signIn(page, DEMO.customer)
    await page.reload()
    await openRequest(page)
    await fillToDetails(page)
    await next(page)
    await dialog(page).getByRole('button', { name: 'اعرض الموقع بالعربي' }).click()
    await expect(dialog(page).getByRole('heading', { name: 'راجعي طلبك' })).toBeVisible()
    await expect(dialog(page).getByText('لمسة كروم')).toBeVisible()
    await expect(dialog(page).getByText('القاهرة الجديدة', { exact: false }).first()).toBeVisible()
    await dialog(page).getByRole('button', { name: 'View the site in English' }).click()
    await expect(dialog(page).getByText('Chrome finish')).toBeVisible()
  })

  test('closing keeps the request; reopening resumes it and focus returns', async ({ page }) => {
    await openRequest(page)
    await dialog(page).getByText('New Cairo', { exact: true }).click()
    await next(page)
    await page.keyboard.press('Escape')
    await expect(dialog(page)).toHaveCount(0)
    const opener = test.info().project.name === 'mobile' ? page.locator('main').getByRole('button', { name: 'Request an appointment' }).first() : page.locator('header').getByRole('button', { name: 'Request an appointment' })
    await expect(opener).toBeFocused()
    await openRequest(page)
    await expect(dialog(page).getByRole('heading', { name: 'What would you like?' })).toBeVisible()
  })

  test('a double tap on Send creates only one request', async ({ page }) => {
    const phone = uniquePhone()
    const api = await apiAs()
    await api.post('/api/auth/signup', { data: { firstName: 'Dina', phone, password: 'dina-pass-2026', lang: 'en' } })
    await signIn(page, { phone, password: 'dina-pass-2026' })
    await page.reload()
    await openRequest(page)
    await fillToDetails(page)
    await next(page)
    const send = dialog(page).getByRole('button', { name: 'Send request' })
    await send.dblclick()
    await expect(dialog(page).getByRole('heading', { name: 'Request sent' })).toBeVisible()
    const list = (await (await api.get('/api/requests')).json()) as { requests: unknown[] }
    expect(list.requests).toHaveLength(1)
    await api.dispose()
  })

  test('if the session ends before sending, the customer can sign in again without losing the request', async ({ page, guard }) => {
    guard.allow(/http 401: POST \/api\/requests/)
    guard.allow(/status of 401/)
    await signIn(page, DEMO.customer)
    await page.reload()
    await openRequest(page)
    await fillToDetails(page)
    await next(page)
    await signOut(page)
    await dialog(page).getByRole('button', { name: 'Send request' }).click()
    await expect(dialog(page).getByRole('heading', { name: 'How can the branch reach you?' })).toBeVisible()
    await dialog(page).getByRole('tab', { name: 'Log in' }).click()
    await dialog(page).getByLabel('Mobile number').fill(DEMO.customer.phone)
    await dialog(page).getByLabel('Password', { exact: true }).fill(DEMO.customer.password)
    await dialog(page).getByRole('button', { name: 'Log in', exact: true }).click()
    await expect(dialog(page).getByText(`Signed in as ${DEMO.customer.name}`)).toBeVisible()
    await next(page)
    await expect(dialog(page).getByText('Chrome finish')).toBeVisible()
  })
})

test.describe('staff on the public site', () => {
  test('are asked to log out before requesting as a customer', async ({ page }) => {
    await signIn(page, DEMO.staff)
    await page.goto('/')
    await page.evaluate(() => sessionStorage.clear())
    await page.reload()
    await openRequest(page)
    await fillToDetails(page)
    await expect(dialog(page).getByText('This is a staff account.', { exact: false })).toBeVisible()
    await expect(dialog(page).getByRole('button', { name: 'Continue' })).toHaveCount(0)
    await dialog(page).getByRole('button', { name: 'Log out' }).click()
    await expect(dialog(page).getByRole('tab', { name: 'New account' })).toBeVisible()
  })
})

test.describe('customer abroad', () => {
  test.use({ timezoneId: 'America/Los_Angeles' })
  test('dates follow Cairo, not the device', async ({ page }) => {
    await page.goto('/')
    await openRequest(page)
    await dialog(page).getByText('New Cairo', { exact: true }).click()
    await next(page)
    await dialog(page).getByText('Help me choose', { exact: true }).click()
    await next(page)
    await expect(dialog(page).getByLabel('Preferred date')).toHaveAttribute('min', cairoDate(0))
  })
})
