/** Staff dashboard copy. Loaded only with /admin. `ar` is type-checked against `en`. */
import { useI18n } from '../i18n/I18nProvider'

const en = {
  title: 'Staff dashboard',
  viewSite: 'View website',
  signedIn: (name: string) => `Signed in as ${name}`,
  logOut: 'Log out',
  allBranches: 'All branches',
  branchScope: (branch: string) => `${branch} branch`,
  tabs: { requests: 'Requests', customers: 'Customers', staff: 'Staff' },
  loginTitle: 'Staff sign-in',
  loginHelp: 'Use the mobile number and password your manager set up for you.',
  notStaffTitle: 'This area is for Lush staff',
  notStaffBody: 'You are signed in with a customer account.',
  offline: 'The Lush server can’t be reached. Check the connection and reload.',
  loading: 'Loading…',
  refresh: 'Refresh',
  updated: (time: string) => `Updated ${time}`,
  search: 'Search',
  searchPlaceholder: 'Name, mobile or reference',
  branch: 'Branch',
  type: 'Type',
  allTypes: 'All types',
  appointment: 'Appointment',
  bridal: 'Bridal',
  filters: {
    today: 'Today',
    open: 'Needs reply',
    contacted: 'In touch',
    confirmed: 'Confirmed',
    closed: 'Closed',
    all: 'All',
  },
  columns: {
    received: 'Received',
    customer: 'Customer',
    services: 'Services',
    when: 'Date & time',
    branch: 'Branch',
    status: 'Status',
  },
  preferred: 'preferred',
  anyTime: 'any time',
  helpMeChoose: 'Help me choose',
  look: 'Look',
  emptyRequests: 'No requests here.',
  emptySearch: 'No requests match your search.',
  loadError: 'Requests couldn’t be loaded.',
  retry: 'Try again',
  status: {
    new: 'New',
    contacted: 'Contacted',
    confirmed: 'Confirmed',
    declined: 'Declined',
    cancelled: 'Cancelled',
    completed: 'Completed',
    no_show: 'No-show',
  } as Record<string, string>,
  detail: {
    close: 'Close',
    customer: 'Customer',
    call: 'Call',
    whatsapp: 'WhatsApp',
    email: 'Email',
    request: 'Request',
    preferredDate: 'Preferred date',
    preferredTime: 'Preferred time',
    confirmedFor: 'Confirmed for',
    eventDate: 'Event date',
    groupSize: 'Group size',
    notes: 'Customer notes',
    noNotes: 'No notes.',
    language: 'Language',
    menuPrices: 'Menu prices when requested',
    actions: 'Update status',
    markContacted: 'Mark as contacted',
    confirm: 'Confirm appointment',
    reschedule: 'Change confirmed time',
    decline: 'Decline',
    cancel: 'Cancel appointment',
    complete: 'Mark completed',
    noShow: 'Mark no-show',
    reopen: 'Reopen',
    date: 'Date',
    time: 'Time',
    messageToCustomer: 'Message to the customer',
    messageHint: 'Optional. Shown in their account.',
    save: 'Save',
    back: 'Back',
    internalNote: 'Internal note',
    internalNoteHint: 'Only staff see notes.',
    addNote: 'Add note',
    history: 'History',
    saved: 'Saved.',
    events: {
      created: 'Request sent',
      status: 'Status changed',
      note: 'Note',
      cancelled_by_customer: 'Cancelled by the customer',
    } as Record<string, string>,
    by: (name: string) => `by ${name}`,
  },
  customers: {
    title: 'Customers',
    help: 'Customers create their own accounts when they request an appointment.',
    requests: 'Requests',
    lastRequest: 'Last request',
    joined: 'Joined',
    resetCode: 'Reset code',
    empty: 'No customers found.',
    searchPlaceholder: 'Name, mobile or email',
    seeRequests: (name: string) => `See ${name}’s requests`,
  },
  reset: {
    title: 'Password reset code',
    body: (name: string) => `Give this code to ${name} by phone or WhatsApp. It works once and expires in 30 minutes.`,
    expires: (time: string) => `Expires at ${time}`,
    done: 'Done',
    confirmTitle: (name: string) => `Create a reset code for ${name}?`,
    confirmBody: 'Any previous code stops working.',
    create: 'Create code',
    cancel: 'Cancel',
  },
  staff: {
    title: 'Staff',
    help: 'Admins see every branch and manage staff. Staff with a branch see only that branch.',
    add: 'Add staff member',
    firstName: 'First name',
    phone: 'Mobile number (login)',
    email: 'Email',
    password: 'Temporary password',
    passwordHint: 'At least 8 characters. Share it privately.',
    role: 'Role',
    roles: { staff: 'Staff', admin: 'Admin' } as Record<string, string>,
    branch: 'Branch',
    anyBranch: 'All branches',
    create: 'Create account',
    created: 'Staff account created.',
    active: 'Active',
    disabled: 'Disabled',
    disable: 'Disable',
    enable: 'Enable',
    you: 'you',
  },
  errors: {
    invalid_transition: 'That change isn’t possible from the current status. Refresh and try again.',
    self_lockout: 'You can’t disable your own account or remove your own admin role.',
    not_found: 'That item no longer exists.',
    date: 'Choose a date.',
    datePast: 'That date has passed. Choose today or a later day.',
    dateFar: 'Choose a date within the next 12 months.',
    time: 'Choose a time.',
    note: 'Write a note first.',
  } as Record<string, string>,
}

export type AdminStrings = typeof en

const ar: AdminStrings = {
  title: 'لوحة الموظفين',
  viewSite: 'الموقع',
  signedIn: (name: string) => `مسجل باسم ${name}`,
  logOut: 'تسجيل الخروج',
  allBranches: 'كل الفروع',
  branchScope: (branch: string) => `فرع ${branch}`,
  tabs: { requests: 'الطلبات', customers: 'العملاء', staff: 'الموظفين' },
  loginTitle: 'دخول الموظفين',
  loginHelp: 'استخدمي رقم الموبايل وكلمة السر اللي المدير عملهم لك.',
  notStaffTitle: 'الجزء ده لموظفين لاش',
  notStaffBody: 'انتي داخلة بحساب عميلة.',
  offline: 'مش قادرين نوصل لسيرفر لاش. اتأكدي من الاتصال وحدثي الصفحة.',
  loading: 'جاري التحميل…',
  refresh: 'تحديث',
  updated: (time: string) => `آخر تحديث ${time}`,
  search: 'بحث',
  searchPlaceholder: 'الاسم أو الموبايل أو رقم الطلب',
  branch: 'الفرع',
  type: 'النوع',
  allTypes: 'كل الأنواع',
  appointment: 'ميعاد',
  bridal: 'عرايس',
  filters: {
    today: 'النهارده',
    open: 'محتاج رد',
    contacted: 'تم التواصل',
    confirmed: 'مؤكد',
    closed: 'مقفول',
    all: 'الكل',
  },
  columns: {
    received: 'وصل',
    customer: 'العميلة',
    services: 'الخدمات',
    when: 'اليوم والوقت',
    branch: 'الفرع',
    status: 'الحالة',
  },
  preferred: 'مفضل',
  anyTime: 'أي وقت',
  helpMeChoose: 'محتاجة مساعدة في الاختيار',
  look: 'الشكل',
  emptyRequests: 'مفيش طلبات هنا.',
  emptySearch: 'مفيش طلبات مطابقة للبحث.',
  loadError: 'مقدرناش نحمّل الطلبات.',
  retry: 'جربي تاني',
  status: {
    new: 'جديد',
    contacted: 'تم التواصل',
    confirmed: 'مؤكد',
    declined: 'مرفوض',
    cancelled: 'ملغي',
    completed: 'تم',
    no_show: 'محضرتش',
  } as Record<string, string>,
  detail: {
    close: 'إغلاق',
    customer: 'العميلة',
    call: 'اتصال',
    whatsapp: 'واتساب',
    email: 'الإيميل',
    request: 'الطلب',
    preferredDate: 'اليوم المفضل',
    preferredTime: 'الوقت المفضل',
    confirmedFor: 'متأكد يوم',
    eventDate: 'ميعاد المناسبة',
    groupSize: 'العدد',
    notes: 'ملاحظات العميلة',
    noNotes: 'مفيش ملاحظات.',
    language: 'اللغة',
    menuPrices: 'أسعار المنيو وقت الطلب',
    actions: 'تحديث الحالة',
    markContacted: 'تم التواصل',
    confirm: 'تأكيد الميعاد',
    reschedule: 'تغيير الميعاد المؤكد',
    decline: 'رفض',
    cancel: 'إلغاء الميعاد',
    complete: 'تم',
    noShow: 'محضرتش',
    reopen: 'إعادة فتح',
    date: 'اليوم',
    time: 'الوقت',
    messageToCustomer: 'رسالة للعميلة',
    messageHint: 'اختياري. بتظهر في حسابها.',
    save: 'حفظ',
    back: 'رجوع',
    internalNote: 'ملاحظة داخلية',
    internalNoteHint: 'الموظفين بس اللي بيشوفوا الملاحظات.',
    addNote: 'إضافة ملاحظة',
    history: 'السجل',
    saved: 'اتحفظ.',
    events: {
      created: 'الطلب اتبعت',
      status: 'الحالة اتغيرت',
      note: 'ملاحظة',
      cancelled_by_customer: 'العميلة لغت الطلب',
    } as Record<string, string>,
    by: (name: string) => `بواسطة ${name}`,
  },
  customers: {
    title: 'العملاء',
    help: 'العملاء بيعملوا حساباتهم بنفسهم لما يطلبوا ميعاد.',
    requests: 'الطلبات',
    lastRequest: 'آخر طلب',
    joined: 'انضمت',
    resetCode: 'كود كلمة السر',
    empty: 'مفيش عملاء.',
    searchPlaceholder: 'الاسم أو الموبايل أو الإيميل',
    seeRequests: (name: string) => `طلبات ${name}`,
  },
  reset: {
    title: 'كود تغيير كلمة السر',
    body: (name: string) => `ادي الكود ده لـ ${name} بالتليفون أو واتساب. بيشتغل مرة واحدة ولمدة 30 دقيقة.`,
    expires: (time: string) => `بينتهي الساعة ${time}`,
    done: 'تمام',
    confirmTitle: (name: string) => `تعملي كود تغيير كلمة السر لـ ${name}؟`,
    confirmBody: 'أي كود قديم هيبطل يشتغل.',
    create: 'اعملي الكود',
    cancel: 'إلغاء',
  },
  staff: {
    title: 'الموظفين',
    help: 'المديرين بيشوفوا كل الفروع وبيديروا الموظفين. الموظف المربوط بفرع بيشوف الفرع ده بس.',
    add: 'إضافة موظف',
    firstName: 'الاسم الأول',
    phone: 'رقم الموبايل (للدخول)',
    email: 'الإيميل',
    password: 'كلمة سر مؤقتة',
    passwordHint: '8 حروف أو أرقام على الأقل. ابعتيها بشكل خاص.',
    role: 'الدور',
    roles: { staff: 'موظف', admin: 'مدير' } as Record<string, string>,
    branch: 'الفرع',
    anyBranch: 'كل الفروع',
    create: 'اعملي الحساب',
    created: 'حساب الموظف اتعمل.',
    active: 'شغال',
    disabled: 'موقوف',
    disable: 'إيقاف',
    enable: 'تفعيل',
    you: 'انتي',
  },
  errors: {
    invalid_transition: 'التغيير ده مش ممكن من الحالة الحالية. حدثي الصفحة وجربي تاني.',
    self_lockout: 'مينفعش توقفي حسابك أو تشيلي صلاحية المدير من نفسك.',
    not_found: 'العنصر ده مبقاش موجود.',
    date: 'اختاري اليوم.',
    datePast: 'اليوم ده عدى. اختاري النهارده أو يوم بعده.',
    dateFar: 'اختاري يوم خلال الـ ١٢ شهر الجايين.',
    time: 'اختاري الوقت.',
    note: 'اكتبي الملاحظة الأول.',
  } as Record<string, string>,
}

export const adminStrings = { en, ar } as const

export function useAdminStrings() {
  const { lang } = useI18n()
  return adminStrings[lang]
}
